[package]
name = "sleitnick/spring"
description = "Critically damped spring"
version = "1.0.0"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
