[package]
name = "sleitnick/comm"
description = "Comm library for remote communication"
version = "0.3.1"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@1"
Option = "sleitnick/option@1"
Promise = "evaera/promise@4"
